export const error = (reason: number) => {
	throw reason;
};
