export const error = (assertion: unknown) => {
	throw assertion;
};
